# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
      - '../src/Partners/DataReceiver/functions.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Partners\DataReceiver\IAmsterdam\IAmsterdamReceiver:
    factory: [ 'App\Partners\DataReceiver\IAmsterdam\IAmsterdamReceiver', 'create' ]
    arguments:
      $stabFilePath: '%kernel.project_dir%/data-sources/temps.xml'

  App\Partners\DataReceiver\Bbc\BbcReceiver:
    factory: [ 'App\Partners\DataReceiver\Bbc\BbcReceiver', 'create' ]
    arguments:
      $stabFilePath: '%kernel.project_dir%/data-sources/temps.json'

  App\Partners\DataReceiver\WeatherCom\WeatherComReceiver:
    factory: [ 'App\Partners\DataReceiver\WeatherCom\WeatherComReceiver', 'create' ]
    arguments:
      $stabFilePath: '%kernel.project_dir%/data-sources/temps.csv'

  App\Weather\ScaleConvertor\ScaleConvertor:
    arguments:
      $strategies: [ '@App\Weather\ScaleConvertor\Strategy\CelsiusToFahrenheit', '@App\Weather\ScaleConvertor\Strategy\FahrenheitToCelsius' ]

  App\Partners\DataImporter\PartnerDataImporter:
    arguments:
      $receivers: [ '@App\Partners\DataReceiver\IAmsterdam\IAmsterdamReceiver', '@App\Partners\DataReceiver\Bbc\BbcReceiver', '@App\Partners\DataReceiver\WeatherCom\WeatherComReceiver' ]
      $scaleConvertor: '@App\Weather\ScaleConvertor\ScaleConvertor'

  App\Api\Controller\WeatherApiController:
    tags: [ controller.service_arguments ]